export enum CONSTANTS {
    USER_WELCOME_EMAIL_NOTIFICATION = 'USER_WELCOME_EMAIL_NOTIFICATION',
    EMAIL_OTP = 'EMAIL_OTP',
    EMAIL_PASSWD_RESET_OTP = 'EMAIL_PASSWD_RESET_OTP',
    TTL_3_HR = 10800,
    TTL_10_MIN = 600,
}
